services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: loinc-ssidl-backend
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: loinc-ssidl-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_node_modules:
  frontend_node_modules:
